FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build

WORKDIR /src

COPY . .

# Compilation de l'application en mode Release
# Le résultat est placé dans le dossier /app
RUN dotnet publish -c Release -o /app

FROM mcr.microsoft.com/dotnet/runtime:7.0

WORKDIR /app

# Copie uniquement les fichiers compilés depuis l'étape "build"
# Cela permet de réduire la taille de l'image final
COPY --from=build /app .

CMD ["dotnet", "Worker.dll"]